export { default as ListIngredients } from './listIngredients/ListIngredients'
export { default as ListIngredientsInPizza } from './listIngredientsInPizza/ListIngredientsInPizza'
export { default as ModalConfirmPizza } from './modalConfirmPizza/ModalConfirmPizza'
export { default as SiderLayout } from './sider/Sider'
export { default as StatisticComp } from './statistic/Statistics'
